### ISSUE TITLE
AWVS Encoder?

### ISSUE THREAD

**Issue by testanull** [gatlindada/awvs-decode#1]
Hi there,
Do you have the encoder for these unpacked script?
I 'm trying to modify some script but haven't know how to repack yet
Thanks

**Comment by gatlindada** [comment]
@testanull refer: [https://github.com/gatlindada/awvs-decode/blob/master/awvs-repack.py](https://github.com/gatlindada/awvs-decode/blob/master/awvs-repack.py) 
Enjoy yourself ^_^

**Comment by testanull** [comment]
> @testanull refer: https://github.com/gatlindada/awvs-decode/blob/master/awvs-repack.py
> Enjoy yourself ^_^

Thank you very much!

**Comment by gatlindada** [comment]
@testanull There seems to be a bug, and I am sorry for this. I will fix it later, use [https://github.com/gatlindada/awvs-decode/blob/master/awvs-repack-protoc.py](https://github.com/gatlindada/awvs-decode/blob/master/awvs-repack-protoc.py) instead
